#!/bin/bash

# Generates a plot using GNU Octave, and puts it in its proper place for serving.

set -e

cd m

PLOTNAME="$1"
PLOTBASENAME="../hugo/static/plots/$PLOTNAME"

PLOTNAME="$PLOTNAME" PLOTBASENAME="$PLOTBASENAME" \
	octave --no-gui --no-history --no-init-file --no-site-file --silent --norc --eval 'generate_plot();'

sed --in-place --file=../plot_svg.sed "$PLOTBASENAME.svg"
