#!/bin/bash

# Generates a plot using Python, and puts it in its proper place for serving.

set -e

PLOTNAME="$1"

PLOTBASENAME="../hugo/static/plots/$PLOTNAME"

# Only use dashes in file names, never underscores. Underscores makes remark
# complain, as it sees them as emphasis markers.
# TODO: this is silly, we should really fix remark instead.
#       https://github.com/remarkjs/remark/issues/253
PLOTBASENAME="${PLOTBASENAME//_/-}"

cd python

# SVG preamble is to ensure the font can be found.
# Note: it's best to ensure this is the exact same URL as the one in the theme,
# such that only one HTTP request needs to be made.
python3 -m factualaudio.generate_plot "factualaudio.plots.$PLOTNAME" \
	--png-output "$PLOTBASENAME.png" --svg-output "$PLOTBASENAME.svg" \
	--svg-preamble '<?xml-stylesheet type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300&amp;subset=latin,cyrillic-ext,latin-ext,cyrillic" ?>'
