#!/bin/bash

# Generates the plots, the site and then postprocesses the site for production.
# All other options are passed to hugo.

set -e
set -o pipefail
shopt -s nullglob
shopt -s dotglob
shopt -s globstar

DESTINATION_DIR="$1"
shift
BASEURL="$1"
shift

./generate-plots
hugo --source hugo --destination "$DESTINATION_DIR/raw" --baseURL "$BASEURL" "$@"
cp -pr "$DESTINATION_DIR"/raw "$DESTINATION_DIR"/cooked
./postprocess-site "$DESTINATION_DIR/cooked" "$BASEURL"
mv "$DESTINATION_DIR"/cooked/* "$DESTINATION_DIR"/
rmdir "$DESTINATION_DIR"/cooked

