#!/bin/bash

# Regenerates the hugo/static/plots directory.

set -e

rm -rf hugo/static/plots
mkdir -p hugo/static/plots

for PLOTPATH in m/plots/*.m
do
	PLOTFILE="${PLOTPATH##*/}"
	PLOTNAME="${PLOTFILE%.m}"
	echo "GENERATING: $PLOTNAME"
	./generate-plot "$PLOTNAME"
done
