#!/bin/bash

# Postprocesses the site, i.e. optimizes it for production serving.
# This step is always optional and is not supposed to result in any
# externally visible changes to the site, aside from performance.

set -e
set -o pipefail
shopt -s nullglob
shopt -s dotglob
shopt -s globstar

[[ "$#" -eq 2 ]]
SITE_DIR="$1"
BASEURL="$2"

HTML_FILES=()
for HTML_FILE in "$SITE_DIR"/**/*.html
do
	# Don't process redirect pages.
	[[ "$(grep --count --fixed-strings '<meta http-equiv="refresh"' -- "$HTML_FILE")" -eq 1 ]] && continue
	HTML_FILES+=("$HTML_FILE")
done

tidyhtml() {
	# We stop tidy from dropping empty elements because that results in
	# FontAwesome <i> tags being removed.

	tidy --drop-empty-elements false -numeric -indent -wrap 0 -quiet "$@"
}

for HTML_FILE in "${HTML_FILES[@]}"
do
	echo "Sanitizing $HTML_FILE" >&2
	tidyhtml -asxml -modify "$HTML_FILE"
done

echo 'Concatenating assets' >&2
ASSET_CONCATENATION_MANIFEST="$SITE_DIR/ASSET-CONCATENATION-MANIFEST"
xsltproc --output "$ASSET_CONCATENATION_MANIFEST" generate-concatenate-manifest.xsl "$SITE_DIR"/index.html
./concatenate-assets "$SITE_DIR" "$BASEURL" < "$ASSET_CONCATENATION_MANIFEST"

echo 'Fingerprinting asssets' >&2
FINGERPRINT_RENAME_MANIFEST="$SITE_DIR/FINGERPRINT-RENAME-MANIFEST.xml"
./fingerprint-assets "$SITE_DIR" "$BASEURL" > "$FINGERPRINT_RENAME_MANIFEST"

for HTML_FILE in "${HTML_FILES[@]}"
do
	echo "Replacing assets for $HTML_FILE" >&2

	# Double-check that every page has the same concatenated assets as /index.html, to prevent potential inconsistencies.
	xsltproc generate-concatenate-manifest.xsl "$HTML_FILE" | cmp "$ASSET_CONCATENATION_MANIFEST"

	xsltproc replace-concatenated-assets.xsl "$HTML_FILE" |
	xsltproc --stringparam manifest "$FINGERPRINT_RENAME_MANIFEST" replace-links.xsl - |
	sed '2 i <!DOCTYPE html>' |
	tidyhtml -ashtml --doctype html5 -output "$HTML_FILE.final"
	mv "$HTML_FILE.final" "$HTML_FILE"
done

